version: '3.8'

services:
  tomcat:
    build:
      context: ./backend
    environment:
      JAVA_OPTS: >
        -Xms512m -Xmx1024m
        -Dspring.profiles.active=qa
        -DPOSTGRES_URL=jdbc:postgresql://host.docker.internal:5432/journal
        -DPOSTGRES_USERNAME=postgres
        -DPOSTGRES_PASSWORD=toor
    ports:
      - "8083:8080"
