version: '3.8'

services:
  tomcat:
    build:
      context: ./backend
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -Dspring.profiles.active=qa -DJWT_SECRET_KEY=${JWT_SECRET_KEY} -DPOSTGRES_URL=${POSTGRES_URL} -DPOSTGRES_USERNAME=${POSTGRES_USERNAME} -DPOSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8083:8080"
